USE [master]
GO
/****** Object:  Database [Ferreteria2.11]    Script Date: 28/08/2017 23:30:11 ******/
CREATE DATABASE [Ferreteria2.11]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ferreteria2.11', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Ferreteria2.11.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Ferreteria2.11_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Ferreteria2.11_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Ferreteria2.11] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ferreteria2.11].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Ferreteria2.11] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET ARITHABORT OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Ferreteria2.11] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Ferreteria2.11] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Ferreteria2.11] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Ferreteria2.11] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Ferreteria2.11] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Ferreteria2.11] SET  MULTI_USER 
GO
ALTER DATABASE [Ferreteria2.11] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Ferreteria2.11] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Ferreteria2.11] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Ferreteria2.11] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [Ferreteria2.11]
GO
/****** Object:  Table [dbo].[CLIENTES]    Script Date: 28/08/2017 23:30:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CLIENTES](
	[id_cliente] [tinyint] NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[apellidoP] [varchar](50) NOT NULL,
	[apellidoM] [varchar](50) NOT NULL,
	[direccion] [varchar](100) NOT NULL,
	[telefono] [varchar](50) NOT NULL,
	[celular] [varchar](50) NOT NULL,
	[email] [varchar](50) NOT NULL,
	[RFC] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED 
(
	[id_cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DETALLE_VENTA]    Script Date: 09/10/2017 23:30:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DETALLE_VENTA](
	[id_producto] [tinyint] NOT NULL,
	[cantidad] [int] NOT NULL,
	[precio] [money] NOT NULL,
	[total] [money] NOT NULL,
	[cambio] [money] NOT NULL,
	[id_folio] [tinyint] NOT NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[EMPLEADO]    Script Date: 09/10/2017 23:30:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[EMPLEADO](
	[id_empleado] [tinyint] NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[apellidoP] [varchar](50) NOT NULL,
	[apellidoM] [varchar](50) NOT NULL,
	[telefono] [varchar](50) NOT NULL,
	[celular] [varchar](50) NOT NULL,
 CONSTRAINT [PK_EMPLEADO] PRIMARY KEY CLUSTERED 
(
	[id_empleado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
